Add more integration tests and clean up the output
rh-pre-commit.version: 2.0.0.dev0
rh-pre-commit.check-secrets: ENABLED

diff --git a/rh-pre-commit/tests/integration/common/setup b/rh-pre-commit/tests/integration/common/setup
--- a/rh-pre-commit/tests/integration/common/setup
+++ b/rh-pre-commit/tests/integration/common/setup
@@ -3,45 +3,28 @@ set -eou pipefail
 
 export project_dir="$(cd ../../ && pwd)"
 export base_repos="$(mktemp -d)"
+export log_file="$(mktemp -d)/test.log"
 
-if [[ "$(id -u)" == "0" ]]
-then
-  curl -o /etc/pki/ca-trust/source/anchors/2015-RH-IT-Root-CA.pem \
-    https://certs.corp.redhat.com/certs/2015-IT-Root-CA.pem &> /dev/null
+function log {
+  echo ${@} | tee -a "${log_file}"
+}
 
-  curl -o /etc/pki/ca-trust/source/anchors/2022-IT-Root-CA.pem \
-    https://certs.corp.redhat.com/certs/2022-IT-Root-CA.pem &> /dev/null
-
-  update-ca-trust &> /dev/null
-fi
-
-# By using this repo we confirm the existing history isn't an issue
-git clone https://github.com/leaktk/fake-leaks.git "${base_repos}/fake-leaks"
-cd "${base_repos}/fake-leaks"
-
-if ! git config user.email &> /dev/null
-then
-  git config --global user.email "no-reply@redhat.com"
-  git config --global user.name "No Reply"
-fi
-
-echo ">>> Install hooks"
-cd "${project_dir}" && make install &> /dev/null
-
-# Configure and install hooks
-echo ">>> Configure hooks"
-cd "${base_repos}"
-python3 -m "${HOOK}" --hook-type pre-commit configure --configure-git-template --force &> /dev/null
-python3 -m "${HOOK}" --hook-type commit-msg configure --configure-git-template --force &> /dev/null
-python3 -m "${HOOK}" --hook-type pre-commit install --force --path "${base_repos}" &> /dev/null
-python3 -m "${HOOK}" --hook-type commit-msg install --force --path "${base_repos}" &> /dev/null
+function test-case {
+  log
+  log "TEST:" ${@}
+}
 
 function pass {
-  echo "${1} (PASS)"
+  log "- ${1} (PASS)"
 }
 
 function fail {
-  echo "${1} (FAIL)"
+  log "- ${1} (FAIL)"
+  echo "====================================================================="
+  echo "Log output"
+  echo "---------------------------------------------------------------------"
+  cat "${log_file}"
+  echo "====================================================================="
   exit 1
 }
 
@@ -49,5 +32,39 @@ function new-repo {
   cd $(mktemp -d)
   cp -r "${base_repos}/fake-leaks" ./fake-leaks
   cd ./fake-leaks
-  echo ">>> Change repo to $(pwd)"
 }
+
+log "Running setup"
+
+if [[ "$(id -u)" == "0" ]]
+then
+  curl -o /etc/pki/ca-trust/source/anchors/2015-RH-IT-Root-CA.pem \
+    https://certs.corp.redhat.com/certs/2015-IT-Root-CA.pem &>> "${log_file}"
+
+  curl -o /etc/pki/ca-trust/source/anchors/2022-IT-Root-CA.pem \
+    https://certs.corp.redhat.com/certs/2022-IT-Root-CA.pem &>> "${log_file}"
+
+  update-ca-trust &>> "${log_file}"
+fi
+
+# By using this repo we confirm the existing history isn't an issue
+git clone https://github.com/leaktk/fake-leaks.git "${base_repos}/fake-leaks" &>> "${log_file}"
+cd "${base_repos}/fake-leaks"
+
+if ! git config user.email &>> "${log_file}"
+then
+  git config --global user.email "no-reply@redhat.com"
+  git config --global user.name "No Reply"
+fi
+
+log "Installing hooks"
+cd "${project_dir}" && make install &>> "${log_file}"
+
+# Configure and install hooks
+log "Configuring hooks"
+cd "${base_repos}"
+python3 -m "${HOOK}" --hook-type pre-commit configure --configure-git-template --force &>> "${log_file}"
+python3 -m "${HOOK}" --hook-type commit-msg configure --configure-git-template --force &>> "${log_file}"
+python3 -m "${HOOK}" --hook-type pre-commit install --force --path "${base_repos}" &>> "${log_file}"
+python3 -m "${HOOK}" --hook-type commit-msg install --force --path "${base_repos}" &>> "${log_file}"
+
diff --git a/rh-pre-commit/tests/integration/test-hook b/rh-pre-commit/tests/integration/test-hook
--- a/rh-pre-commit/tests/integration/test-hook
+++ b/rh-pre-commit/tests/integration/test-hook
@@ -3,17 +3,37 @@
 # WARNING: these tests are run on the host too. Try to make sure that
 # they aren't destructive and work outside of a container
 #
+#
+# General test case format:
+#
+# -----------------------------------------------------------------------------
+#
+# test-case "Confirm ...."
+#
+# <set-up commands>
+#
+# tests with pass/fail messages called to show the results
+#
+# <tear-down commands>
+#
+# -----------------------------------------------------------------------------
+#
+# And new-repo can be called to create a fresh copy of the repo. The extra
+# comments around it are to help make this more obvious
+#
+# If fail is called, the contents of ${log_file} are displayed. Both pass and
+# fail also log to the log_file
+#
 set -euo pipefail
 
 HOOK="${1}"
 GITREF="${2}"
 ENVTYPE="${3}"
 
-echo ">> Run setup"
-
 source ./common/setup
 
-echo ">> Test Hook: ${HOOK}"
+log
+log "Testing Hook: ${HOOK}"
 
 # New Repo ####################################################################
 new-repo
@@ -21,82 +41,93 @@ new-repo
 
 if [[ "${HOOK}" = "rh_pre_commit.multi" ]]
 then
-  echo ">>> Confirm local config disabled by default for multi installs"
+  test-case "Confirm local config disabled by default for multi installs"
 
-  if grep "enableLocalConfig\s*=\s*false" ~/.gitconfig &> /dev/null
+  if grep "enableLocalConfig\s*=\s*false" ~/.gitconfig &>> "${log_file}"
   then
-    pass ">>>> local config disabled by default"
+    pass "local config disabled by default"
   else
-    fail ">>>> local config not disabled by default"
+    fail "local config not disabled by default"
   fi
 else
   if [[ "${ENVTYPE}" == "container" ]]
   then
-    echo ">>> Confirm local config setting not set for normal installs"
+    test-case "Confirm local config setting not set for normal installs"
 
-    if grep "enableLocalConfig" ~/.gitconfig &> /dev/null
+    if grep "enableLocalConfig" ~/.gitconfig &>> "${log_file}"
     then
-      fail ">>>> enableLocalConfig should not be set for ${HOOK}"
+      fail "enableLocalConfig should not be set for ${HOOK}"
     else
-      pass ">>>> enableLocalConfig not set for ${HOOK}"
+      pass "enableLocalConfig not set for ${HOOK}"
     fi
-  else
-    # Containers have a known clean state and other things might not
-    echo ">>> Skipping confirm local config setting not set for normal installs for env type ${ENVTYPE}"
   fi
 fi
 
-echo ">>> Confirm the pre-commit hook template is installed"
+# -----------------------------------------------------------------------------
 
-if grep "${HOOK}" ~/.git-template/hooks/pre-commit &> /dev/null
+test-case "Confirm the pre-commit hook template is installed"
+
+if grep "${HOOK}" ~/.git-template/hooks/pre-commit &>> "${log_file}"
 then
-  pass ">>>> ${HOOK} type:pre-commit installed"
+  pass "${HOOK} type:pre-commit installed"
 else
-  fail ">>>> ${HOOK} type:pre-commit not installed"
+  fail "${HOOK} type:pre-commit not installed"
 fi
 
-echo ">>> Confirm the commit-msg hook template is installed"
+# -----------------------------------------------------------------------------
 
-if grep "${HOOK}" ~/.git-template/hooks/commit-msg &> /dev/null
+test-case "Confirm the commit-msg hook template is installed"
+
+if grep "${HOOK}" ~/.git-template/hooks/commit-msg &>> "${log_file}"
 then
-  pass ">>>> ${HOOK} template type:commit-msg installed"
+  pass "${HOOK} template type:commit-msg installed"
 else
-  fail ">>>> ${HOOK} template type:commit-msg not installed"
+  fail "${HOOK} template type:commit-msg not installed"
 fi
 
-echo ">>> Confirm it doesn't block on secrets that are not staged during a commit"
+# -----------------------------------------------------------------------------
+
+test-case "Confirm it doesn't block on secrets that are not staged during a commit"
+
 echo 'secret="EdnBsJW59yS6bGxhXa5+KkgCr1HKFv5g"' > secret
 
-if git commit --allow-empty -m "This should pass" &> /dev/null
+if git commit --allow-empty -m "This should pass" &>> "${log_file}"
 then
-  pass ">>>> ${HOOK} unstaged secret not blocked"
+  pass "${HOOK} unstaged secret not blocked"
 else
-  fail ">>>> ${HOOK} unstaged secret blocked"
+  fail "${HOOK} unstaged secret blocked"
 fi
 
-echo ">>> Confirm staged secrets are caught"
+# -----------------------------------------------------------------------------
+
+test-case "Confirm staged secrets are caught"
+
 git add secret
 
-if ! git commit -m "This should error" &> /dev/null
+if ! git commit -m "This should error" &>> "${log_file}"
 then
-  pass ">>>> ${HOOK} detected secrets"
+  pass "${HOOK} detected secrets"
 else
-  fail ">>>> ${HOOK} did not detect secrets"
+  fail "${HOOK} did not detect secrets"
 fi
 
-echo ">>> Confirm a notsecret allows a secret"
+# -----------------------------------------------------------------------------
+
+test-case "Confirm a notsecret allows a secret"
 
 echo 'secret="EdnBsJW59yS6bGxhXa5+KkgCr1HKFv5g" #notsecret' > secret
 git add secret
 
-if git commit -m "This should pass" &> /dev/null
+if git commit -m "This should pass" &>> "${log_file}"
 then
-  pass ">>>> ${HOOK} notsecret comment works"
+  pass "${HOOK} notsecret comment works"
 else
-  fail ">>>> ${HOOK} notsecret comment did not work"
+  fail "${HOOK} notsecret comment did not work"
 fi
 
-echo ">>> Confirm a .gitleaks.toml should allow secrtes"
+# -----------------------------------------------------------------------------
+
+test-case "Confirm a .gitleaks.toml should allow secrtes"
 
 echo 'secret="EdnBsJW59yS6bGxhXa5+KkgCr1HKFv5g"' > secret
 git add secret
@@ -109,60 +140,68 @@ paths = [
 EOF
 git add .gitleaks.toml
 
-if git commit -m "This should pass" &> /dev/null
+if git commit -m "This should pass" &>> "${log_file}"
 then
-  pass ">>>> ${HOOK} allowlist works"
+  pass "${HOOK} allowlist works"
 else
-  fail ">>>> ${HOOK} allowlist did not work"
+  fail "${HOOK} allowlist did not work"
 fi
 
-echo ">>> Confirm it signed off on the commits as ENABLED"
-if git log -n 1 | grep "rh-pre-commit.check-secrets: ENABLED" &> /dev/null
+# -----------------------------------------------------------------------------
+
+test-case "Confirm it signed off on the commits as ENABLED"
+
+if git log -n 1 | grep "rh-pre-commit.check-secrets: ENABLED" &>> "${log_file}"
 then
-  pass ">>>> It was detected as enabled"
+  pass "It was detected as enabled"
 else
-  fail ">>>> It was not detected as enabled"
+  fail "It was not detected as enabled"
 fi
 
 # New Repo ####################################################################
 new-repo
 ###############################################################################
 
-echo ">>> Confirm the check can just be disabled"
+test-case "Confirm the task can just be disabled"
 
 echo 'secret="EdnBsJW59yS6bGxhXa5+KkgCr1HKFv5g"' > secret
 git add secret
 
-if ! git commit -m "This should error" &> /dev/null
+if ! git commit -m "This should error" &>> "${log_file}"
 then
-  pass ">>>> ${HOOK} detected secrets"
+  pass "${HOOK} detected secrets when the task is enabled"
 else
-  fail ">>>> ${HOOK} did not detect secrets"
+  fail "${HOOK} did not detect secrets when the task was enabled"
 fi
 
 git config --bool rh-pre-commit.checkSecrets false
 
-if git commit -m "This should pass" &> /dev/null
+if git commit -m "This should pass" &>> "${log_file}"
 then
-  pass ">>>> ${HOOK} git config works"
+  pass "${HOOK} secrets commited when task disabled"
 else
-  fail ">>>> ${HOOK} git config did not work"
+  fail "${HOOK} secrets could not be commited when the task was disabled"
 fi
 
-echo ">>> Confirm it signed off on the commits as disabled"
+# -----------------------------------------------------------------------------
 
-if git log -n 1 | grep "rh-pre-commit.check-secrets: DISABLED" &> /dev/null
+test-case "Confirm sign-off knows when hooks are disabled"
+
+git config --bool rh-pre-commit.checkSecrets false
+git commit --allow-empty -m "some commit" &>> "${log_file}"
+
+if git log -n 1 | grep "rh-pre-commit.check-secrets: DISABLED" &>> "${log_file}"
 then
-  pass ">>>> It was detected as disabled"
+  pass "It was detected as disabled"
 else
-  fail ">>>> It was not detected as disabled"
+  fail "It was not detected as disabled"
 fi
 
 # New Repo ####################################################################
 new-repo
 ###############################################################################
 
-echo ">>> Confirm the local hook setting is respected"
+test-case "Confirm the local hook setting is respected"
 
 cat > .pre-commit-config.yaml <<EOF
 repos:
@@ -177,35 +216,39 @@ repos:
 EOF
 git add .pre-commit-config.yaml
 
-if git commit -m "This should pass" &> /dev/null
+if git commit -m "This should pass" &>> "${log_file}"
 then
-  pass ">>>> .pre-commit-config.yaml local config ignored"
+  pass ".pre-commit-config.yaml local config ignored"
 else
-  fail ">>>> .pre-commit-config.yaml local config not ignored"
+  fail ".pre-commit-config.yaml local config not ignored"
 fi
 
-echo ">>> Confirm the local hook will run when turned on in the config"
-
-git config --bool rh-pre-commit.enableLocalConfig true
-touch some-file && git add some-file # Force a change for a commit
+# -----------------------------------------------------------------------------
 
 if [[ "${HOOK}" == "rh_pre_commit.multi" ]]
 then
-  echo ">>> Confirm the local config can be enabled for ${HOOK}"
-  if git commit -m "This should error" &> /dev/null
+  test-case "Confirm the local config can be enabled for ${HOOK}"
+
+  git config --bool rh-pre-commit.enableLocalConfig true
+  touch some-file && git add some-file # Force a change for a commit
+
+  if git commit -m "This should error" &>> "${log_file}"
   then
-    fail ">>>> .pre-commit-config.yaml local config not applied"
+    fail ".pre-commit-config.yaml local config not applied"
   else
-    pass ">>>> .pre-commit-config.yaml local config applied"
+    pass ".pre-commit-config.yaml local config applied"
   fi
 else
-  echo ">>> Confirm the local config cannot be enabled for ${HOOK}"
+  test-case "Confirm the local config cannot be enabled for ${HOOK}"
 
-  if git commit -m "This should pass" &> /dev/null
+  git config --bool rh-pre-commit.enableLocalConfig true
+  touch some-file && git add some-file # Force a change for a commit
+
+  if git commit -m "This should pass" &>> "${log_file}"
   then
-    pass ">>>> .pre-commit-config.yaml local config ignored"
+    pass ".pre-commit-config.yaml local config ignored"
   else
-    fail ">>>> .pre-commit-config.yaml local config not ignored"
+    fail ".pre-commit-config.yaml local config not ignored"
   fi
 fi
 
@@ -213,67 +256,205 @@ fi
 new-repo
 ###############################################################################
 
-echo ">>> Replace hook with pre-commit.com"
+test-case "Confirm it's not enabled for this repo yet and sign-off blocks it"
+# This is because we have the commit-msg installed but not the pre-commit
+# hook in any way
 
-python3 -m pre_commit install -f &> /dev/null
-if grep "${HOOK}" .git/hooks/pre-commit &> /dev/null
-then
-  fail ">>>> ${HOOK} not replaced"
-fi
-
-echo ">>> Confirm it's not enabled for this repo yet and sign off blocks it"
-
+python3 -m pre_commit install --hook-type pre-commit -f &>> "${log_file}"
 echo 'secret="EdnBsJW59yS6bGxhXa5+KkgCr1HKFv5g"' > secret-not-caught
 cat > .pre-commit-config.yaml <<EOF
 repos: []
 EOF
 git add .pre-commit-config.yaml secret-not-caught
 
-if git commit -m "This should error" &> /dev/null
+if grep "${HOOK}" .git/hooks/pre-commit &>> "${log_file}"
 then
-  fail ">>>> Sign-off did not catch the commit"
+  fail "${HOOK} not pre-commit hook replaced"
 else
-  pass ">>>> Sign-off caught the commit when it wasn't disabled"
+  pass "${HOOK} pre-commit hook replaced"
 fi
 
-echo ">>> Confirm it's not enabled for this repo yet and sign off has been turned off"
+if git commit -m "Sign-off should stop the commit" &>> "${log_file}"
+then
+  fail "Sign-off did not catch the commit"
+else
+  pass "Sign-off caused the commit to fail because rh-pre-commit wasn't installed"
+fi
+
+# -----------------------------------------------------------------------------
+
+test-case "Confirm pre-commit not enabled for this repo yet and sign-off has been turned off"
+# With both pre-commit and commit-msg off we should be able to commit secrets
+# to the repo now
 
 git config --bool rh-pre-commit.commit-msg.signOff false
 
-if git commit -m "This should pass" &> /dev/null
+if git commit -m "This should pass" &>> "${log_file}"
 then
-  pass ">>>> Secret not caught yet"
+  pass "Secret not caught yet"
 else
-  fail ">>>> Secret detected when it shouldn't be"
+  fail "Secret detected when it shouldn't be"
 fi
 
-echo ">>> Confirm it can be installed through its .pre-commit-hooks.yaml"
+if git log -n 1 | grep "rh-pre-commit" &>> "${log_file}"
+then
+  fail "Sign-off was still enabled"
+else
+  pass "Sign-off was disabled properly"
+fi
 
+# -----------------------------------------------------------------------------
+
+test-case "Confirm both pre-commit and commit-msg can be installed through its .pre-commit-hooks.yaml"
+
+git config --bool rh-pre-commit.commit-msg.signOff true
+python3 -m pre_commit install --hook-type commit-msg -f &>> "${log_file}"
 cat > .pre-commit-config.yaml <<EOF
 repos:
   - repo: https://gitlab.corp.redhat.com/infosec-public/developer-workbench/tools.git
     rev: ${GITREF}
     hooks:
       - id: rh-pre-commit
+      - id: rh-pre-commit.commit-msg
 EOF
 mv secret-not-caught secret
 git add .pre-commit-config.yaml secret
 
-if git commit -m "This should error" &> /dev/null
+if grep "${HOOK}" .git/hooks/pre-commit &>> "${log_file}"
 then
-  fail ">>>> Secret not caught"
+  fail "${HOOK} not pre-commit hook replaced"
 else
-  pass ">>>> Secret caught"
+  pass "${HOOK} pre-commit hook replaced"
 fi
 
-echo ">>> Confirm it doesn't block on secrets that are not staged during a commit"
+if grep "${HOOK}" .git/hooks/commig-msg &>> "${log_file}"
+then
+  fail "${HOOK} commit-msg hook not replaced"
+else
+  pass "${HOOK} commmit-msg hook replaced"
+fi
 
-git commit --no-verify -m "Commit staged to get it out of the way" &> /dev/null
+if git commit -m "This should error" &>> "${log_file}"
+then
+  fail "Secret not caught"
+else
+  pass "Secret caught"
+fi
+
+# -----------------------------------------------------------------------------
+
+test-case "Confirm it doesn't block on secrets that are not staged during a commit"
+
+git commit --no-verify -m "Commit staged to get it out of the way" &>> "${log_file}"
 echo 'secret="EdnBsJW59yS6bGxhXa5+KkgCr1HKFv5g"' > unstaged
 
-if git commit --allow-empty -m "This should pass" &> /dev/null
+if git commit --allow-empty -m "This should pass" &>> "${log_file}"
 then
-  pass ">>>> Unstaged secret not blocked"
+  pass "Unstaged secret not blocked"
 else
-  fail ">>>> Unstaged secret blocked"
+  fail "Unstaged secret blocked"
 fi
+
+rm unstaged
+
+# -----------------------------------------------------------------------------
+
+test-case "Confirm it signed off on the commits as ENABLED (i.e. it detected it from the .pre-commit-config.yaml in the repo)"
+
+if git log -n 1 | grep "rh-pre-commit.check-secrets: ENABLED" &>> "${log_file}"
+then
+  pass "It was detected as enabled"
+else
+  fail "It was not detected as enabled"
+fi
+
+# -----------------------------------------------------------------------------
+
+if [[ "${ENVTYPE}" == "container" ]]
+then
+
+  test-case "Confirm it doesn't fail if the cached patterns exist but the creds don't"
+
+  SAVED_TOKEN="${LEAKTK_PATTERN_SERVER_AUTH_TOKEN}"
+  unset LEAKTK_PATTERN_SERVER_AUTH_TOKEN
+  echo 'Hello, world!' > some-file
+  git add some-file
+
+  if git commit -m "This should pass" &>> "${log_file}"
+  then
+    pass "rh-gitleaks ran without an issue"
+  else
+    fail "rh-gitleaks ran with issues"
+  fi
+
+  export LEAKTK_PATTERN_SERVER_AUTH_TOKEN="${SAVED_TOKEN}"
+  unset SAVED_TOKEN
+
+  # ---------------------------------------------------------------------------
+
+  test-case "Confirm it shows a helpful login message when it can't contact the pattern server"
+
+  SAVED_TOKEN="${LEAKTK_PATTERN_SERVER_AUTH_TOKEN}"
+  unset LEAKTK_PATTERN_SERVER_AUTH_TOKEN
+  rm -rf ~/.cache/rh-gitleaks
+  echo 'Hello (again), world!' > some-other-file
+  git add some-other-file
+
+  commit_output="$(git commit -m "This should error" 2>&1 || true)"
+
+  if echo "${commit_output}" | grep 'Could not find pattern server auth token' &>> "${log_file}"
+  then
+    pass "A failure reason was provided"
+  else
+    fail "A failure reason not was provided"
+  fi
+
+  if echo "${commit_output}" | grep 'Please log in with this command and try again' &>> "${log_file}"
+  then
+    pass "Login instructions were provided"
+  else
+    fail "Login instructions were not provided"
+  fi
+
+  if echo "${commit_output}" | grep '/python3 -m rh_gitleaks login' &>> "${log_file}"
+  then
+    pass "A login example was provided"
+  else
+    fail "A login example was not provided"
+  fi
+
+  git rm -f some-other-file &>> "${log_file}"
+  export LEAKTK_PATTERN_SERVER_AUTH_TOKEN="${SAVED_TOKEN}"
+  unset SAVED_TOKEN
+fi
+
+# New Repo ####################################################################
+new-repo
+###############################################################################
+
+test-case "Confirm ammends don't double add the sign-off"
+
+touch some-file
+git add some-file
+git commit -m "Add some file" &>> "${log_file}"
+enabled_str="rh-pre-commit.check-secrets: ENABLED"
+
+if git log -n 1 | grep "${enabled_str}" &>> "${log_file}"
+then
+  pass "The inital sign-off is there"
+else
+  fail "The inital sign-off not is there"
+fi
+
+git commit --amend -m "Add some file" &>> "${log_file}"
+
+enabled_count="$(git log -n 1 | grep "${enabled_str}" | sort | uniq -c | awk '{print $1}')"
+
+if [[ "${enabled_count}" = "1" ]]
+then
+  pass "The sign-off only shows once"
+else
+  fail "The sign-off shows more than once"
+fi
+
+# -----------------------------------------------------------------------------
