Include more test cases
rh-pre-commit.version: 2.0.0.dev0
rh-pre-commit.check-secrets: ENABLED

diff --git a/rh-pre-commit/tests/integration/common/setup b/rh-pre-commit/tests/integration/common/setup
--- a/rh-pre-commit/tests/integration/common/setup
+++ b/rh-pre-commit/tests/integration/common/setup
@@ -4,22 +4,32 @@ set -eou pipefail
 export project_dir="$(cd ../../ && pwd)"
 export test_repos="$(mktemp -d)"
 
+# By using this repo we confirm the existing history isn't an issue
 git clone https://github.com/leaktk/fake-leaks.git "${test_repos}/repo-0"
 
 cd "${test_repos}/repo-0"
 git config --global user.email "integration-test@example.com"
 git config --global user.name "Integration Test"
 
-for x in {1..9}
-do
-  cp -r "${test_repos}/repo-0" "${test_repos}/repo-${x}"
-done
-
-cd "${project_dir}" && make install
+echo -n "Installing tools..."
+cd "${project_dir}" && make install &> /dev/null
 cd "${test_repos}"
+echo "done!"
 
 # Configure it with the default settings
 "${HOOK}" configure --configure-git-template --force
+"${HOOK}" --hook-type commit-msg configure --configure-git-template --force
 
 # Enable it for all existing projects under the home directory
 "${HOOK}" install --force --path "${test_repos}"
+"${HOOK}" --hook-type commit-msg install --force --path "${test_repos}"
+
+
+function pass {
+  echo "${1} (PASS)"
+}
+
+function fail {
+  echo "${1} (FAIL)"
+  exit 1
+}
